version: '3.4'

services:
  neo4j:
    image: neo4j:4.2.2
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]
  server:
    image: aicompetitionplatform
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    depends_on:
      - neo4j
    links:
      - neo4j
  website:
    image: aicompetitionplatformwebsite
    build:
      context: website
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:8080
    links:
      - server
