version: '3.4'

services:
  cits3200project:
    image: cits3200project
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
