version: '3.4'

services:
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4JLABS_PLUGINS=["apoc"]
  server:
    image: aicompetitionplatform
    build:
      context: server
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - neo4j
    links:
      - "neo4j"
