version: '3.4'

services:
  server:
    image: cits3200project
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
  neo4j: 
    image: neo4j
    ports:
    - "7474:7474"
    - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4JLABS_PLUGINS=["apoc"]
