FROM node:lts-alpine
ENV NODE_ENV=test
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm ci && mv node_modules ../
# Does not install through package lock?!
RUN npm i --dev jest
COPY . .
EXPOSE 8080
RUN chown -R node /usr/src/app
USER node
CMD sleep 60 && npm run test
